# -*- coding: utf-8 -*-
"""Fungsi_Laporan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIc_B5lNaywjQ01LvglKQ40EODtgZstT
"""

# laporan.py
def cetak_laporan(data_mahasiswa):
    print("=== LAPORAN DATA MAHASISWA ===")
    for i, mhs in enumerate(data_mahasiswa, start=1):
        print(f"{i}. Nama: {mhs['nam']}, Umur: {mhs['umur']}, Jurusan: {mhs['jurusan']}")
    print(f"Total mahasiswa: {len(data_mahasiswa)}")
