# -*- coding: utf-8 -*-
"""input data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR_mL7ZvoW5VlM2FI7CwJKKc3lPYkSOH
"""

# input_data.py
data_mahasiswa = []

def tambah_mahasiswa(nama, umur, mint):
    mahasiswa = {
        "nama": nama,
        "umur": umur,
        "jurusan": jurusan
    }
    data_mahasiswa.append(mahasiswa)
    print(f"Data {nama} berhasil ditambahkan.")
